### ISSUE TITLE
プロジェクト検索とライブラリ検索を1つにしたい

### ISSUE THREAD

**Issue by quick-xp** [library-miner/library-miner-frontyard#13]
仕様変更依頼

初期構想では、目的別検索について
　1. プロジェクト検索 ・・・ライブラリ名からプロジェクトを検索
　2. ライブラリ検索・・・ライブラリ名からライブラリを検索 
としていたが、どちらも同じ 画面から検索できるようにしたい（プロジェクト/ライブラリ検索）

目的別検索が一つ減るが、そこには プロジェクト名で プロジェクト（ライブラリ除く）を検索できる機能を追加したい　（現状では プロジェクト名 から 検索が不可のため）

![_2016-03-20_17_26_47](https://cloud.githubusercontent.com/assets/3175028/13903568/3826c668-eec4-11e5-9061-a4f833920117.jpg)

![_2016-03-20_17_27_21](https://cloud.githubusercontent.com/assets/3175028/13903569/3f917e8e-eec4-11e5-8b7b-ebc4f1dba4ac.jpg)

**Comment by quick-xp** [comment]
利用プロジェクト 検索の 追加プルダウン はデフォルトでは プロジェクト/ライブラリ 両方を検索対象とし、前画面にて 利用プロジェクト とおした場合は プロジェクトのみをデフォルト、利用ライブラリをおした場合はライブラリのみをデフォルトしたい　可能か？

**Comment by nishio-dens** [comment]
プロジェクト、ライブラリの件数をそれぞれ出すのはAPI側を改修しないといけない。
今は プロジェクト・ライブラリの 件数を混ぜて表示するようにしている。
