### ISSUE TITLE
サイトデザインの修正

### ISSUE THREAD

**Issue by quick-xp** [library-miner/library-miner-frontyard#22]
完成に向けてサイトデザインの見直しを行う

アイデアが浮かばないので試行錯誤で

**Comment by nishio-dens** [comment]
ok

**Comment by quick-xp** [comment]
feature/20160322-r-1 
トップページを考えてみた　どう？
<img width="1280" alt="2016-03-24 0 33 18" src="https://cloud.githubusercontent.com/assets/3175028/13990604/532d28e4-f158-11e5-81d4-ebad914e77ea.png">

**Comment by nishio-dens** [comment]
凄く良いと思う
これって html?  または  まだデザインの状態でhtmlに起こしたほうがよい？

**Comment by quick-xp** [comment]
上記ははめ込み画像ではなく実画面。
コード適当だけどPR出す

**Comment by quick-xp** [comment]
ライブラリMinerとは の部分修正してみた。
どうか？

![2016-03-25 0 03 18](https://cloud.githubusercontent.com/assets/3175028/14021028/10312b88-f21d-11e5-8f6a-f30fb9b0d87d.png)
